### PR TITLE
Delete all

### PR DESCRIPTION
**Pull request by markrickert**
- Adds `.delete(key)`. and `.delete_all!` to android version
- Adds `.delete_all` to iOS version.
- Restructures tests to be more internally consistent by deleting everything after each test.
- Adds tests for `.delete_all`

:pray:

### CODE REVIEW

**Comment by markrickert** [comment]
FYI - I didn't just iterate over `all` and call `delete` for performance reasons... the `delete` method will call `.synchronize` each time and we only want to call that at the end of our batch delete once.

**Comment by GantMan** [comment]
very cool

**Comment by emtee** [comment]
@markrickert PP.delete_all! results in NoMethodError: undefined method `settings' for Module:Module.
I guess you missed the following code in your method definitions for delete & delete_all!
_settings = get_settings_

**Comment by markrickert** [comment]
Ahh thanks, @emtee! Would you mind
 sending a pull request to fix it?

**Comment by emtee** [comment]
Yeah, on it.

**Comment by GantMan** [comment]
Released new version with fix!

**Pull request merged**
